#!/usr/bin/env python3
"""
Email Distribution System for Meeting Summaries
Sends formatted meeting summaries via email
"""

import os
import smtplib
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from datetime import datetime
import markdown

class EmailSender:
    """Send meeting summaries via email"""
    
    def __init__(self, config_file=None):
        """
        Initialize email sender
        
        Args:
            config_file: Path to email config JSON
        """
        if config_file is None:
            config_file = Path(__file__).parent / "email_config.json"
        
        self.config_file = Path(config_file)
        self.config = self._load_config()
    
    def _load_config(self):
        """Load email configuration"""
        if not self.config_file.exists():
            return self._create_default_config()
        
        with open(self.config_file) as f:
            return json.load(f)
    
    def _create_default_config(self):
        """Create default configuration file"""
        default_config = {
            "smtp_server": "smtp.gmail.com",
            "smtp_port": 587,
            "from_email": "your-email@gmail.com",
            "from_name": "8825 Meeting Automation",
            "recipients": {
                "tgif_team": [
                    "justin@example.com",
                    "tricia@example.com",
                    "josh@example.com"
                ]
            },
            "templates": {
                "weekly_summary": {
                    "subject": "TGIF Weekly Meeting Summary: {start_date} to {end_date}",
                    "intro": "Here's your automated weekly summary of TGIF meetings.",
                    "footer": "Generated by 8825 Meeting Automation System"
                }
            }
        }
        
        # Save default config
        with open(self.config_file, 'w') as f:
            json.dump(default_config, f, indent=2)
        
        print(f"📝 Created default config: {self.config_file}")
        print(f"   Please update with your email settings")
        
        return default_config
    
    def send_meeting_summary(self, summary, subject=None, recipients=None, template="weekly_summary"):
        """
        Send meeting summary via email
        
        Args:
            summary: Markdown summary text
            subject: Email subject (or use template)
            recipients: List of email addresses (or use config)
            template: Template name from config
            
        Returns:
            True if sent successfully
        """
        # Get template
        template_config = self.config.get("templates", {}).get(template, {})
        
        # Get recipients
        if recipients is None:
            recipients = self.config.get("recipients", {}).get("tgif_team", [])
        
        if not recipients:
            print("❌ No recipients configured")
            return False
        
        # Get subject
        if subject is None:
            subject = template_config.get("subject", "Meeting Summary")
        
        # Build email
        msg = self._build_email(summary, subject, template_config)
        
        # Send
        return self._send_email(msg, recipients)
    
    def _build_email(self, summary, subject, template_config):
        """Build email message"""
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = f"{self.config.get('from_name', '8825')} <{self.config.get('from_email')}>"
        
        # Add intro if in template
        intro = template_config.get("intro", "")
        footer = template_config.get("footer", "")
        
        if intro:
            summary = f"{intro}\n\n{summary}"
        
        if footer:
            summary = f"{summary}\n\n---\n\n{footer}"
        
        # Plain text version
        text_part = MIMEText(summary, 'plain')
        msg.attach(text_part)
        
        # HTML version (convert markdown to HTML)
        try:
            html_content = markdown.markdown(summary, extensions=['tables', 'fenced_code'])
            html_styled = self._apply_html_styling(html_content)
            html_part = MIMEText(html_styled, 'html')
            msg.attach(html_part)
        except Exception as e:
            print(f"⚠️  Could not generate HTML version: {e}")
        
        return msg
    
    def _apply_html_styling(self, html_content):
        """Apply CSS styling to HTML email"""
        style = """
        <style>
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
            }
            h1 {
                color: #2c3e50;
                border-bottom: 3px solid #3498db;
                padding-bottom: 10px;
            }
            h2 {
                color: #34495e;
                margin-top: 30px;
                border-bottom: 2px solid #ecf0f1;
                padding-bottom: 5px;
            }
            h3 {
                color: #7f8c8d;
            }
            table {
                border-collapse: collapse;
                width: 100%;
                margin: 20px 0;
            }
            th, td {
                border: 1px solid #ddd;
                padding: 12px;
                text-align: left;
            }
            th {
                background-color: #3498db;
                color: white;
            }
            tr:nth-child(even) {
                background-color: #f9f9f9;
            }
            code {
                background-color: #f4f4f4;
                padding: 2px 6px;
                border-radius: 3px;
                font-family: 'Courier New', monospace;
            }
            ul, ol {
                padding-left: 30px;
            }
            li {
                margin: 8px 0;
            }
            .footer {
                margin-top: 40px;
                padding-top: 20px;
                border-top: 2px solid #ecf0f1;
                color: #7f8c8d;
                font-size: 0.9em;
            }
        </style>
        """
        
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            {style}
        </head>
        <body>
            {html_content}
        </body>
        </html>
        """
    
    def _send_email(self, msg, recipients):
        """Send email via SMTP"""
        try:
            # Check for password
            password = os.environ.get('EMAIL_PASSWORD')
            if not password:
                print("❌ EMAIL_PASSWORD environment variable not set")
                print("   Set with: export EMAIL_PASSWORD='your-app-password'")
                return False
            
            # Connect to SMTP server
            server = smtplib.SMTP(
                self.config.get('smtp_server'),
                self.config.get('smtp_port')
            )
            server.starttls()
            
            # Login
            server.login(
                self.config.get('from_email'),
                password
            )
            
            # Send to each recipient
            msg['To'] = ', '.join(recipients)
            server.send_message(msg)
            
            server.quit()
            
            print(f"✅ Email sent to {len(recipients)} recipient(s)")
            return True
        
        except Exception as e:
            print(f"❌ Failed to send email: {e}")
            return False


def send_meeting_summary(summary, subject, recipients):
    """
    Convenience function for sending meeting summaries
    
    Args:
        summary: Markdown summary text
        subject: Email subject
        recipients: List of email addresses
        
    Returns:
        True if sent successfully
    """
    sender = EmailSender()
    return sender.send_meeting_summary(summary, subject, recipients)


def main():
    """CLI interface for testing"""
    import argparse
    
    parser = argparse.ArgumentParser(description="Send meeting summary via email")
    parser.add_argument("--summary-file", required=True, help="Path to summary markdown file")
    parser.add_argument("--subject", help="Email subject")
    parser.add_argument("--recipients", nargs="+", help="Email addresses")
    parser.add_argument("--test", action="store_true", help="Test mode (print instead of send)")
    
    args = parser.parse_args()
    
    # Load summary
    with open(args.summary_file) as f:
        summary = f.read()
    
    print(f"📧 Preparing to send email...")
    print(f"   Summary: {args.summary_file}")
    print(f"   Length: {len(summary)} chars")
    
    if args.test:
        print("\n" + "="*60)
        print("TEST MODE - Email content:")
        print("="*60)
        print(summary)
        print("="*60)
        return
    
    # Send
    sender = EmailSender()
    success = sender.send_meeting_summary(
        summary=summary,
        subject=args.subject,
        recipients=args.recipients
    )
    
    if success:
        print("\n✅ Email sent successfully")
    else:
        print("\n❌ Failed to send email")


if __name__ == "__main__":
    main()
